---
title: '基本運算子 - 基本數學運算 & 邏輯運算'
author: "Nick Lin"
date: "2020/2/2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## <b>邏輯運算</b>

符號   | 說明  | 範例  | 
-------|:-----:|:-----:|
<      | 小於  |a < b  |
>      | 大於  |a > b  |
<=     | 小於等於  |a <= b  |
>=     | 大於等於  |a >= b  |
%in%   | 是否存在於|A %in% B|
&      | 交集/且 (向量)   | a & b|
&&     | 交集/且 (單一值)  | a && b|
\|      | 聯集/或 (向量)| a \| b|
\|\|      | 聯集/或 (單一值)| a \|\| b|

```{r}
x <- 10
y <- 20

x > 20

x >= 5

x < 5
x <= 10

!(x > 5) # 前面多一個有!否定功能 =>  True 變 False，如是 False 則變 True


x %in% c(5:15)

x > 12 || y > 10

x > 4 && y > 10

z = c(1,5,8)
z > 0 & z >= 2

z > 0 && z >= 2 # && 只比較單一值，只抓 z 的第一元素跟 0 與 2 比較。
```

## <b>基本術運算子</b>

#### <b>運算子 + </b>

說明 : 兩個向量相加

```{r}
a <- c(1,2,3)
b <- c(4,5,6)

a+b

```

#### <b>運算子 - </b>

說明 : 兩個向量相減

```{r}
a <- c(1,2,3)
b <- c(4,5,6)

a-b

```


#### <b>運算子 * </b>

說明 : 兩個向量相乘

```{r}
a <- c(1,2,3)
b <- c(4,5,6)

a*b

```



#### <b>運算子 / </b>

說明 : 兩個向量相除

```{r}
a <- c(1,2,3,0)
b <- c(4,5,6,0)

b/a

```


















