---
title: "流程控制及自訂函數"
author: "Nick"
date: "2020/1/31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 流程控制

## if-else敘述
語法 :  if(condition) expr#1 else expr#2

```{r}
x<-6
if (x>5) y <- 2 else y <- 4
y

```

語法 : if(condition) {expr#1,...,expr#n } else {expr#1,...,expr#m}

```{r}
x<-6
y<-1
c<-0

if (x>5 && y <3){
    x<-x-1;
    y<-y+1;
  
}else{
    c<-3
}

x
y
c

```


語法 : if(condition) exp#1

```{r}
x<-6
if (x<10) y<-5
y
```

語法 : ifelse(condition,a,b)

```{r}

x<-6
y = ifelse (x<10,5,10) 
y

```


## if-else if-else敘述


```{r}
score<-70
if(score>=60){
  print("PASS")
}else if(score>=80){
  print("Good")
}else{
  print("Fail")
}
```



### <b> switch敘述</b>

語法 : switch(condition,expr#1,expr#2,...,expr#n)

```{r}
x<-1
switch(x,3,sum(1:5),sum(1:10))
x<-2
switch(x,3,sum(1:5),sum(1:10))
x<-3
switch(x,3,sum(1:5),sum(1:10))
x<-4
switch(x,3,sum(1:5),sum(1:10)) # 無回傳值


```


```{r}

y<-"meat"

switch(y,juice ="apple",meat="beef")

```


<br>

## <b>迴圈控制</b>

### <b>For Loop</b>

語法 : 

- for (index in expr#1) expr#2
- for (index in expr#1) {expr#2;...;expr#n}
```{r}
x <-0
for (i in 1:10) x<-x+i
x
```
```{r}
x<-0
y<-1
for (i in 1:10) {
  x<-x+i
  y<-y*x
}

x
y

```

### <b>While Loop</b>

語法 : 
- while (condition) expr#1
- while (condition) {expr#1;...;expr#m}

```{r}
sum <-0
i<-1
while(i<=10){
  sum <- sum+i;
  i<-i+1;
}

sum

```

### <b>Repeat & Break</b>
```{r}
sum <-0
i<-0
repeat{
  sum<-sum+1
  i<-i+1
  if (i>10)break
}
sum
```

### <b>Next</b>
```{r}
sum <-0

for (i in 1:50) {
  
if (i %% 2 == 0) next
    sum<-sum+1
}
sum

```




# 自訂函數

```{r}

calculate_squared <- function(x) {
  
  x_squared <- x**2
  
  
  return(x_squared)
}


calculate_squared(5)

#a = calculate_squared(5)
#a

calculate_squared(1:10)

#b = calculate_squared(1:10)
#b


```

```{r}

get_bmi <- function(height, weight) {
  
  height <- height/100
  
  bmi <- weight / height**2
  
  return(bmi)
}

get_bmi(173, 72)

get_bmi(c(180, 75), c(158, 50))

```




```{r}

circle_calculator <- function(r = 2, is_area = TRUE) {
  
  area <- pi * r**2  # R 內建圓周率 pi
  
  perimeter <- 2 * pi * r
  
  if (is_area) {
    return(area)
  
    } else {
    
      return(perimeter)
  }
}
circle_calculator(,) # 預設回傳圓形面積
circle_calculator(3, FALSE) # 回傳圓形周長

```




```{r}
bmi_calculator <- function(height, weight) {
  height <- height/100
  bmi <- weight / height**2
  if (bmi < 18.5) {
    bmi_label <- "輕"
  } else if (bmi > 30) {
    bmi_label <- "胖"
  } else if (bmi >= 18.5 & bmi < 25) {
    bmi_label <- "正常"
  } else {
    bmi_label <- "過重"
  }
  bmi_list <- list(
    bmi = bmi,
    label = bmi_label
  )
  return(bmi_list)
}
shaq <- bmi_calculator(173, 70)
shaq$bmi
shaq$label

```


# 例外處理

```{r}
# 沒有例外處理
custom_as_numeric <- function(x) {
  return(as.numeric(x))
}
custom_as_numeric(TRUE)
custom_as_numeric("TRUE")

# 有例外處理
custom_as_numeric <- function(x) {
  tryCatch({
    return(as.numeric(x))
  },
  warning = function(w) {
    return("請勿輸入文字向量。")
  })
}
custom_as_numeric(TRUE)
custom_as_numeric("TRUE")
```
































